---
# defaults/main.yml (zookeeper)
# Prefix : zookeeper

- name: Install tasks
  import_tasks: install.yml
  when:
    - zookeeper_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
