---
platforms:
  - name: ${MOLECULE_DISTRO}-${ANSIBLE_VER}-a
    source:
      alias: ubuntu/${MOLECULE_DISTRO}/amd64

  - name: ${MOLECULE_DISTRO}-${ANSIBLE_VER}-b
    source:
      alias: ubuntu/${MOLECULE_DISTRO}/amd64

  - name: ${MOLECULE_DISTRO}-${ANSIBLE_VER}-c
    source:
      alias: ubuntu/${MOLECULE_DISTRO}/amd64
